### ISSUE TITLE
Badges UX not good 

### ISSUE THREAD

**Issue by happylolonly** [scroll-tech/frontends#1230]
After click on badge card and returning back, state is reset, and need to clicking again. Very annoying

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/05a62415-34dd-4ab5-988c-bf5252ee7a78">

**Comment by febryardiansyah** [comment]
this is true, as a user i'am really tired to scrolling again after open one of badge. the feature must be added would be either enabling right click to open new page or handle previous scrolling state on back.

**Comment by Holybasil** [comment]
pls view badges through https://scroll.io/canvas-and-badges

**Comment by happylolonly** [comment]
> pls view badges through https://scroll.io/canvas-and-badges

Begin better, but it is still not link, not possible to open in new tab.
Web core UX...
