### ISSUE TITLE
[BUG] Scroll Origins NFT not working for mint

### ISSUE THREAD

**Issue by happylolonly** [scroll-tech/frontends#1231]
Scroll Origins NFT not working for mint. Seems some bug.

<img width="769" alt="image" src="https://github.com/user-attachments/assets/6f1d5a7e-3e28-4135-94de-f4d6050518a5">

**Comment by happylolonly** [comment]
Begin to work, strange...

**Comment by Oyase-shinobi** [comment]
Hello @happylolonly
I have checked your github and very interested in this
may I take this issue?

Thank you
