### ISSUE TITLE
[BUG] scroll bridge  无法正常识别eth 主网余额

### ISSUE THREAD

**Issue by lcmmhcc** [scroll-tech/frontends#815]
**Describe the bug**
连接[scroll.io](https://scroll.io/bridge) bridge 无法识别 eth 余额

**To Reproduce**

![image](https://github.com/scroll-tech/frontends/assets/37269413/66b7e1e4-08a0-4e4e-83d6-cd5a82b9820e)
![image](https://github.com/scroll-tech/frontends/assets/37269413/2ee3f6dc-e201-4f9e-b29d-e20a43814050)

**Expected behavior**

如上图，应该能够识别出来有 0.01ETH 但是 显示0 balance

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - mac OS 13.4
 - Browser 
 - Chrome 已是最新版本
版本 119.0.6045.159（正式版本） (arm64) 
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by Holybasil** [comment]
@lcmmhcc 
Based on the screenshot, it appears that the website has not retrieved your wallet balance yet. Clicking the "Max" button at this time will display "No Balance". The "Max" button will only function once your balance is displayed on the page.
