### ISSUE TITLE
[BUG]Load more button

### ISSUE THREAD

**Issue by mefefirat** [scroll-tech/frontends#996]
After entering the NFT tab under the ecosystem, when we press the load more button, the first data comes, but if I press the load more button for the second time, the page gives an error.

You can find the video link below

https://github.com/scroll-tech/frontends/assets/7009824/9d7ccd87-3c5f-452a-a76f-aad94b530764

**Comment by dazaart** [comment]
looks like this issue was solved

**Comment by Oyase-shinobi** [comment]
hello @mefefirat 
in this page, I think we should have not only Load more button but also a Load less button
in you website, because there is no load less button, a lot of the users is not comfortable for using it now

this is my short opinion
Thank you
